<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <GenerateModVersion>true</GenerateModVersion>
        <TargetFramework>net6.0</TargetFramework>
        <AssemblyName>AyarabuMod</AssemblyName>
        <Product>AyarabuMod</Product>
        <RootNamespace>AyarabuMod</RootNamespace>
        <Authors>Jitsu</Authors>
        <Version>1.0.0</Version>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <DebugType>none</DebugType>
        <DependencyRoot Condition="'$(DependencyRoot)' == ''"
            >$(ModRepositoryRoot)dependencies</DependencyRoot>
        <MelonLoaderReferenceDirectory Condition="'$(MelonLoaderReferenceDirectory)' == ''"
            >$(DependencyRoot)/melonloader/net6</MelonLoaderReferenceDirectory>
        <GameInteropReferenceDirectory Condition="'$(GameInteropReferenceDirectory)' == ''"
            >$(DependencyRoot)/interop/assemblies</GameInteropReferenceDirectory>
    </PropertyGroup>
    <ItemGroup>
        <Reference
            Include="MelonLoader"
            HintPath="$(MelonLoaderReferenceDirectory)/MelonLoader.dll"
            Private="false"
        />
        <Reference
            Include="0Harmony"
            HintPath="$(MelonLoaderReferenceDirectory)/0Harmony.dll"
            Private="false"
        />
        <Reference
            Include="Il2CppInterop.Runtime"
            HintPath="$(MelonLoaderReferenceDirectory)/Il2CppInterop.Runtime.dll"
            Private="false"
        />
        <Reference
            Include="Assembly-CSharp"
            HintPath="$(GameInteropReferenceDirectory)/Assembly-CSharp.dll"
            Private="false"
        />
        <Reference
            Include="Il2Cppmscorlib"
            HintPath="$(GameInteropReferenceDirectory)/Il2Cppmscorlib.dll"
            Private="false"
        />
        <Reference
            Include="UnityEngine.CoreModule"
            HintPath="$(GameInteropReferenceDirectory)/UnityEngine.CoreModule.dll"
            Aliases="UnityCore"
            Private="false"
        />
    </ItemGroup>
    <Import Project="$(ModRepositoryRoot)build/SharedDependencies.props" />
</Project>
